---
title: "R Notebook"
# output: html_notebook
---

# Load
```{r}
library(dplyr)
library(ggplot2)

df <- read.csv("../data/311_feb.csv")
```

# Clean
```{r}
 # get top 15 complaints
w = table(df$Complaint.Type)
t = as.data.frame(w)
names(t)[1] = 'Complaint.Type'
ct <- head(t[order(t$Freq, decreasing = TRUE),c(1,2)], 15)$Complaint.Type
df_complaints <- df[df$Complaint.Type %in% ct,]

# Select only Borough and Complaint.Type columns 
# Reorganzie the data frame and make Borough into indvidual columns.
df_select <- select(df_complaints, Borough, Complaint.Type)
df_tally <- df_select %>% group_by(Borough, Complaint.Type) %>% tally()
df_tally$Borough <- chartr(" ", ".", df_tally$Borough) # "Staten Island" should be "Staten.Island"
```

# Plot
```{r}
my_theme <- theme(plot.title = element_text(family = "Helvetica", face = "bold", size = (25)), 
                    plot.subtitle=element_text(family = "Helvetica", face = "bold", size = (25)),
                    axis.text.x = element_text(angle = 0, hjust = .5),
                    legend.title = element_text(face = "bold.italic", family = "Helvetica", size=20), 
                    legend.text = element_text(face = "italic", family = "Helvetica", size=13), 
                    axis.title = element_text(family = "Helvetica", size = (20)),
                    axis.text = element_text(family = "Courier", size = (13)))

ggplot(df_tally, aes(x=factor(Borough), y=n, fill=Complaint.Type)) +
  geom_bar(stat='identity', position='dodge') +
  labs(
        title = "What Does Each Borough Complain About",
        x = "Borough", 
        y = "Number of Complaints"
      ) +
  scale_fill_viridis(discrete=TRUE) + 
  theme_bw() + 
  my_theme +
  coord_flip()
```

