---
title: "R Notebook"
# output: html_notebook
---

```{r, fig.width=16}
library(dplyr)
library(ggplot2)

# load data
df <- read.csv("data/311_feb.csv")

# get top 15 complaints
w = table(df$Complaint.Type)
t = as.data.frame(w)
names(t)[1] = 'Complaint.Type'
ct <- head(t[order(t$Freq, decreasing = TRUE),c(1,2)], 15)$Complaint.Type
df_complaints <- df[df$Complaint.Type %in% ct,]

# Select only Borough and Complaint.Type columns 
# Reorganzie the data frame and make Borough into indvidual columns.
df_select <- select(df_complaints, Borough, Complaint.Type)
df_tally <- df_select %>% group_by(Borough, Complaint.Type) %>% tally()
df_tally$Borough <- chartr(" ", ".", df_tally$Borough) # "Staten Island" should be "Staten.Island"

# plot
ggplot(df_tally, aes(x=factor(Complaint.Type), y=n, fill=Borough)) +
  geom_bar(stat='identity', position='dodge') +
  coord_flip()
```

```{r}
df_tally
```


```{r}
ggplot(df_tally, aes(x=factor(Complaint.Type), y=n, fill=Borough)) +
  geom_bar(stat='identity', position='dodge') +
  coord_flip()
```

```{r}
write.csv(df_tally, row.names=F, file = "311_borough_bar_plot.csv")
```


```{r}
df_tally[df_tally$Borough %in% c('BROOKLYN'), ]
```





```{r, fig.width=16}
ggplot(df_test, aes(x=factor(Complaint.Type), y=n, fill=Borough)) +
  geom_bar(stat='identity', position='dodge') +
  coord_flip()
```
```{r}
mpg
```

```{r}
ggplot(mpg, aes(class)) +
  geom_bar(aes(fill=drv))
```

